services:

  backend:
    image: api
    build: ../backend/
    env_file:
      - ../backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - mosquitto
      - influxdb

  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    env_file:
      - influxdb.env
    volumes:
      - influxdb-data:/var/lib/influxdb2

  node-red:
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - type: bind
        source: ./node-red
        target: /data

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - type: bind
        source: "./mosquitto/config/"
        target: "/mosquitto/config/"
      - mosquitto-data:/mosquitto/data/
      - mosquitto-log:/mosquitto/log/
      - type: bind
        source: "./mosquitto/security/"
        target: "/mosquitto/security/"

volumes:
  influxdb-data:
  mosquitto-data:
  mosquitto-log:
